prefix = /usr

all:

install:
	install -d $(DESTDIR)$(prefix)/lib/wp360-test-tools
	install usr/lib/wp360-test-tools/avg.lua $(DESTDIR)$(prefix)/lib/wp360-test-tools
	install usr/lib/wp360-test-tools/clock.sh $(DESTDIR)$(prefix)/lib/wp360-test-tools
	install usr/lib/wp360-test-tools/graph.lua $(DESTDIR)$(prefix)/lib/wp360-test-tools
	install usr/lib/wp360-test-tools/run.screen $(DESTDIR)$(prefix)/lib/wp360-test-tools
	install usr/lib/wp360-test-tools/run.sh $(DESTDIR)$(prefix)/lib/wp360-test-tools

.PHONY: all install
